services:
  postgres:
    image: postgres:17
    container_name: car-rental-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: car_rental_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      OTP_EXPIRATION_TIME_MS: ${OTP_EXPIRATION_TIME_MS}
      OTP_MAX_GENERATION_ATTEMPTS: ${OTP_MAX_GENERATION_ATTEMPTS}
      OTP_MAX_VERIFICATION_ATTEMPTS: ${OTP_MAX_VERIFICATION_ATTEMPTS}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
