spring:
  application:
    name: car-rental-service

  datasource:
    url: jdbc:postgresql://localhost:5432/car_rental_db?options=-c%20timezone=UTC
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true

server:
  port: 8080